[project]
name = "china-english-words"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "english-words>=2.0.2",
    "pymupdf>=1.27.2.3",
    "pypdf>=6.12.1",
    "requests>=2.34.2",
    "spacy>=3.8.14",
    "stanfordnlp>=0.2.0",
    "stanza>=1.12.0",
    "transformers[torch]>=5.9.0",
    "wordfreq>=3.1.1",
]
